### ISSUE TITLE
(B) Update user's friends on user login (see comment)

### ISSUE THREAD

**Issue by davidalee** [Bestrida/bestrida-server#115]
Currently, app will only get friends from Strava API if the user is new (i.e. not in our db). If user is already in our db, user's friends are not modified.

We need to change this so that when a user logs in, it will call Strava for user's friends and then iterate over the friends to see which friends (if any) are new and need to be added to our friends array.

Could probably do this by finding all the new friends and pushing them to user's friends array via mongoose $push method

**Comment by giwook** [comment]
This issue isn't urgent...user's friends likely won't get updated that often
