### ISSUE TITLE
(B) What do we do if challenge expires and both users haven't completed? (see comments)

### ISSUE THREAD

**Issue by davidalee** [Bestrida/bestrida-server#73]

**Comment by giwook** [comment]
And how would you check if a challenge has expired? Maybe check due date whenever user views their challenges?

**Comment by jrzimmerman** [comment]
Would we set a timeout of some length depending on the difference of start date and midnight of end date?

**Comment by giwook** [comment]
Maybe if one user completes challenge and one doesn't, we can declare the winner by default. If both users don't complete we can nullify the challenge (don't increment wins/losses/challenge count) and give them an option to renew or set a new challenge
